### ISSUE TITLE
Plugin not able to find qualityGate

### ISSUE THREAD

**Issue by btodd914** [Haufe-Lexware/gocd-plugins#22] opened 2018-01-11 18:25 UTC
![image](https://user-images.githubusercontent.com/13924524/34840265-0f168582-f6ca-11e7-8308-56f5620b2e7b.png)

Have the plugin all set up and I have the quality gate set to the default sonarQube way. But I am still getting an error that it cannot be found. Is there a fix for this or is it just a problem with my set up?

**Comment by edemirkan** [comment] 2018-01-13 22:36
@btodd914 I am getting the same error.
Upon further checking **:9000/api/webservices/list**, I noticed the following. 
[...]
`{"path":"api/resources","since":"2.10","description":"Removed since 6.3, please use api/components and api/measures instead","actions":[{"key":"index","description":"The web service is removed and you're invited to use the alternatives: <ul><li>if you need one component without measures: api/components/show</li><li>if you need one component with measures: api/measures/component</li><li>if you need several components without measures: api/components/tree</li><li>if you need several components with measures: api/measures/component_tree</li></ul>"`
[...]
Which suggests the plugin is outdated and not working with current version (6.7.1) of sonarqube.

**Comment by NahidSiddiqui** [comment] 2018-01-23 16:28
I have a similar issue, I think the problem is, in my case it is using an outdated url. The format for the correct url in my case is: http://<sonar_cube_url>/api/qualitygates/project_status?projectKey=<project_key>

So I agree it is outdated

**Comment by xxBedy** [comment] 2018-01-30 17:20
This fix working for me https://github.com/Haufe-Lexware/gocd-plugins/pull/24

**Comment by charleston10** [comment] 2018-04-18 14:27
@xxBedy Someone will accept/merge your pull request?

**Comment by apansari** [comment] 2018-05-22 19:48
Facing the similar issue. Is there a plan to get the PR merged anytime soon?

**Comment by charleston10** [comment] 2018-06-11 12:32
@apansari I'm trying to solve my profile problem
But you can get the fit through my fork
https://github.com/charleston10/gocd-plugins

**Comment by apansari** [comment] 2018-06-11 13:30
@charleston10 : thanks for sharing. tried installing the plugin from your fork but see below error:

```
13:16:42.064 [go] Start to execute task: Plugin with ID: sonar.quality.gate.plugin.
13:16:42.098 [SonarQube Quality Gate Plugin] configuration setting 'SonarProjectKey' is 'com.example.convoy:convoy-feature-service'
13:16:42.098 [SonarQube Quality Gate Plugin] configuration setting 'StageName' is ''
13:16:42.098 [SonarQube Quality Gate Plugin] configuration setting 'JobCounter' is ''
13:16:42.099 [SonarQube Quality Gate Plugin] configuration setting 'JobName' is ''
13:16:42.099 [SonarQube Quality Gate Plugin] configuration setting 'IssueTypeFail' is 'error'
13:16:42.099 [SonarQube Quality Gate Plugin] configuration setting 'SonarApiUrl' is 'http://********@sonar-wc-1p.sys.net:9000/api'
13:16:42.099 [SonarQube Quality Gate Plugin] checking quality gate result for: com.example.convoy:convoy-feature-service
13:16:42.099 [SonarQube Quality Gate Plugin] API Url: http://********@sonar-wc-1p.sys.net:9000/api
13:16:42.099 [SonarQube Quality Gate Plugin] Fail if: error
13:16:42.223 [SonarQube Quality Gate Plugin] Error during get or parse of quality gate result. Please check if a quality gate is defined
**JSONObject["parameter"] not found**.
13:16:42.233 class org.json.JSONException declares multiple JSON fields named cause
13:16:42.253 [go] Current job status: failed.
```
seems to be an issue with sonar scan itself, any inputs on what must be missing?
https://github.com/charleston10/gocd-plugins/blob/master/sonar-qualitygates-plugin/src/com/tw/go/task/sonarqualitygate/SonarTaskExecutor.java#L56

**Comment by charleston10** [comment] 2018-06-12 18:23
@apansari You can download of Jar
https://github.com/charleston10/gocd-plugins/blob/ff08c52e2cbb71f4a6b16fe36ec51a2b1d03efc8/sonar-qualitygates-plugin/jar/gocd-sonar-qualitygates-plugin-2.0.0.jar

**Comment by ysnoussi** [comment] 2018-10-31 18:35
Could someone merge this PR please!

**Comment by markus2810** [comment] 2018-11-07 08:51
Pull request merged

**Closed as completed** 2018-11-07 08:51 UTC

**Comment by tuyen03a128** [comment] 2019-04-23 09:23
> @charleston10 : thanks for sharing. tried installing the plugin from your fork but see below error:
> 
> ```
> 13:16:42.064 [go] Start to execute task: Plugin with ID: sonar.quality.gate.plugin.
> 13:16:42.098 [SonarQube Quality Gate Plugin] configuration setting 'SonarProjectKey' is 'com.example.convoy:convoy-feature-service'
> 13:16:42.098 [SonarQube Quality Gate Plugin] configuration setting 'StageName' is ''
> 13:16:42.098 [SonarQube Quality Gate Plugin] configuration setting 'JobCounter' is ''
> 13:16:42.099 [SonarQube Quality Gate Plugin] configuration setting 'JobName' is ''
> 13:16:42.099 [SonarQube Quality Gate Plugin] configuration setting 'IssueTypeFail' is 'error'
> 13:16:42.099 [SonarQube Quality Gate Plugin] configuration setting 'SonarApiUrl' is 'http://********@sonar-wc-1p.sys.net:9000/api'
> 13:16:42.099 [SonarQube Quality Gate Plugin] checking quality gate result for: com.example.convoy:convoy-feature-service
> 13:16:42.099 [SonarQube Quality Gate Plugin] API Url: http://********@sonar-wc-1p.sys.net:9000/api
> 13:16:42.099 [SonarQube Quality Gate Plugin] Fail if: error
> 13:16:42.223 [SonarQube Quality Gate Plugin] Error during get or parse of quality gate result. Please check if a quality gate is defined
> **JSONObject["parameter"] not found**.
> 13:16:42.233 class org.json.JSONException declares multiple JSON fields named cause
> 13:16:42.253 [go] Current job status: failed.
> ```
> seems to be an issue with sonar scan itself, any inputs on what must be missing?
> https://github.com/charleston10/gocd-plugins/blob/master/sonar-qualitygates-plugin/src/com/tw/go/task/sonarqualitygate/SonarTaskExecutor.java#L56

@apansari
same issue with me when I use sonarQube 7.2.1. I build a temporarily fixed jar here:
https://github.com/tuyen03a128/gocd-plugins/blob/master/sonar-qualitygates-plugin/jar/gocd-sonar-qualitygates-plugin-2.0.1.jar
and open a pull request. https://github.com/charleston10/gocd-plugins/pull/1

**Comment by aeells** [comment] 2019-04-29 14:06
Comments/status above would seem to suggest a fix has been merged. 
However, I can't see that reflected either in the `sonar-qualitygates-plugin` repo commit history and the wiki is definitely still referencing version 1.0.0 of the jar file https://github.com/Haufe-Lexware/gocd-plugins/blob/master/bin/gocd-sonar-qualitygates-plugin-1.0.0.jar
Can this be clarified please?
As above, I'm still seeing REST call failures with SonarQube 7.1.
```REST call failed; URL=https://.../api/resources?resource=...&metrics=quality_gate_details; Code=404;```
(Replacing with the updated version 2.0.0 supplied above by @charleston10 worked 👍)
https://github.com/charleston10/gocd-plugins/blob/ff08c52e2cbb71f4a6b16fe36ec51a2b1d03efc8/sonar-qualitygates-plugin/jar/gocd-sonar-qualitygates-plugin-2.0.0.jar
